/**
 * 公式テンプレート(工作表2)に埋め込まれている選択肢マスタ。
 *
 * 設計判断:
 * - JSON をランタイムで fetch せず、`as const` の配列としてソースに埋め込む。
 *   書き出す xlsx の値は必ずこのリストのどれかと一字一句一致していなければ、
 *   TWAC 側のデータ入力規則に弾かれる。ネットワーク越しに取りに行くと
 *   「取得に失敗したまま選択肢の無いフォームが出る」という壊れ方をするうえ、
 *   型でも守れない。ここに置けば、リストに無い値を UI から選ぶことはできない。
 * - 値は台湾側の表記(中国語＋英語の連結)そのまま。日本語に訳したり整形したり
 *   しない。表示だけを直したつもりでも、書き出す値まで変わると弾かれる。
 * - **並び順もテンプレートのまま**にする。select の並びが公式と同じであれば、
 *   公式サイトの画面と見比べながら入力できる。
 *
 * ■ 出典と、ズレたときに気付く仕組み
 *   すべて public/assets/taiwan-arrival-card/template.xlsx の非表示シート
 *   工作表2 から機械的に写したもので、範囲は sheet1 のデータ入力規則
 *   (dataValidation)と workbook.xml の定義名が指しているものと同じ。
 *   写し間違いや写し漏れは目視では見つからない(国籍は 258 件ある)ので、
 *   options.test.ts がテンプレートを読み直して**この配列と順序込みで
 *   完全一致するか**を毎回検証している。テンプレートを差し替えたら
 *   そのテストが落ちるので、そうしたらこのファイルを作り直すこと。
 */

/** 国籍が台湾・香港・マカオ・中国以外のときの Visa Type(M 列)。定義名 OtherVisa = 工作表2!$B$2:$B$4 */
export const VISA_TYPE_OTHER = [
  '免簽證 Visa-Exempt(include TAC)',
  '持有簽證(Holding a Visa)',
  '落地簽證Landing Visa/臨時入國Temporary Entry',
] as const

/** 国籍が 'ROC,REPUBLIC OF CHINA(TAIWAN)' のときの Visa Type。定義名 TaiwanVisa = 工作表2!$B$5:$B$6 */
export const VISA_TYPE_TAIWAN = [
  '未具入國許可 Permit-Exempt',
  '具入國許可 Permit',
] as const

/** 国籍が香港・マカオ・中国のときの Visa Type。定義名 ChinaVisa = 工作表2!$B$7 */
export const VISA_TYPE_CHINA = ['入國許可證號'] as const

/** 性別(G 列)。工作表2!$B$12:$B$13 */
export const SEX_OPTIONS = ['Male', 'Female'] as const

/** 台湾での滞在先の種別(AG 列)。工作表2!$B$17:$B$19 */
export const ACCOMMODATION_OPTIONS = [
  'Residential Address',
  'Hotel Name',
  'Transfer',
] as const

/** 渡航目的(AC 列)。工作表2!$E$2:$E$11 */
export const PURPOSE_OPTIONS = [
  '1.商務 Business',
  '2.求學 Study',
  '3.觀光 Sightseeing / Travel / Leisure',
  '4.展覽 Exhibition',
  '5.探親 Visit Relative',
  '6.醫療 Medical Care',
  '7.會議 Conference',
  '8.就業 Employment',
  '9.宗教 Religion',
  '10.其他 Others',
] as const

/** 職業(Q 列)。工作表2!$H$2:$H$43 */
export const OCCUPATION_OPTIONS = [
  '會計員/ACCOUNTANT/CPA',
  '演藝人員/ACTOR/ENTERTAINER',
  '軍人/ARMY/NAVY',
  '藝術家/ARTIST',
  '銀行員/BANKER',
  '商/執行長/總裁/BUSINESS/DIRECTOR/CEO',
  '監護工/CARETAKER',
  '職員/CLERK/EMPLOYEE/STAFF',
  '顧問/CONSULTANT',
  '船員/空服員/CREW/SEAMAN',
  '外交人員/DIPLOMAT',
  '潛水夫/DIVER',
  '醫生/DOCTOR/DENTIST',
  '工程師/建築師/ENGINEER/ARCHITECH',
  '農/FARMER/AGRICULTURE',
  '漁民/FISHERMAN',
  '公務員/GOVERNMENT OFFICER',
  '家庭幫傭/DOMESTIC WORKER/HOUSEHOLD WORKER',
  '家庭照顧者/HOMEMAKER',
  '資訊人員/IT',
  '記者/JOURNALIST/REPORTER',
  '船員(外籍移工)/SEAFARER',
  '律師/LAWYER/ATTORNEY/COUNSEL',
  '技工/MECHANIC/FACTORY WORKER',
  '製造業技工/MANUFACTURE WORKER',
  '音樂家/MUSICIAN',
  '護士/看護婦/NURSE',
  '飛行員/PILOT',
  '傳教士/PRIEST',
  '教授/大學講師/PROFESSOR/LECTURER/INSTRUCTOR',
  '研究人員/RESEARCHER',
  '推銷員/SALESMAN',
  '科學家/SCIENTIST',
  '秘書/SECRETARY',
  '專家/SPECIALIST',
  '學生/STUDENT/SCHOLAR/PUPIL',
  '教師/TEACHER/EDUCATOR',
  '技師/TECHNICIAN',
  '作家/WRITER',
  '無業/NONE/BABY/INFANT',
  '其他(外籍勞工)/OFW',
  '其他/OTHER',
] as const

/**
 * 台湾の県市。工作表2!$K$2:$K$23。
 *
 * テンプレートには載っているが、sheet1 の 34 列のどれにも対応する
 * dataValidation が無いため、現状は書き出しに使っていない。使わないものも
 * 同じ形で残してあるのは、次にテンプレートを取り込み直したときに
 * 「消したのか写し忘れたのか」を区別できるようにするため。
 */
export const CITY_COUNTY_OPTIONS = [
  '臺北市 Taipei City',
  '基隆市 Keelung City',
  '新北市 New Taipei City',
  '宜蘭縣 Yilan County',
  '新竹縣 Hsinchu County',
  '桃園市 Taoyuan City',
  '苗栗縣 Miaoli County',
  '臺中市 Taichung City',
  '彰化縣 Changhua County',
  '南投縣 Nantou County',
  '嘉義縣 Chiayi County',
  '雲林縣 Yunlin County',
  '臺南市 Tainan City',
  '高雄市 Kaohsiung City',
  '澎湖縣 Penghu County',
  '屏東縣 Pingtung County',
  '臺東縣 Taitung County',
  '花蓮縣 Hualien County',
  '金門縣 Kinmen County',
  '連江縣 Lienchiang County',
  '新竹市 Hsinchu City',
  '嘉義市 Chiayi City',
] as const

/** 国籍・出生国・居住国(I / J / L 列)。'JPN,JAPAN' 形式。工作表2!$N$2:$N$259 */
export const NATIONALITY_OPTIONS = [
  'ABW,ARUBA',
  'AFG,AFGHANISTAN',
  'AGO,ANGOLA',
  'ALB,ALBANIA',
  'AND,ANDORRA',
  'ANT,NETHERLANDS ANTILLES',
  'ARE,UNITED ARAB EMIRATES',
  'ARG,ARGENTINA',
  'ARM,ARMENIA',
  'ATF,FRENCH SOUTHERN TERRITORIES',
  'ATG,ANTIGUA AND BARBUDA',
  'AUS,AUSTRALIA',
  'AUT,AUSTRIA',
  'ASM,AMERICAN SAMOA',
  'AZE,AZERBAIJAN',
  'BDI,BURUNDI',
  'BEL,BELGIUM',
  'BEN,BENIN',
  'BFA,BURKINA FASO',
  'BGD,BANG LADESH',
  'BGR,BULGARIA',
  'BHR,BAHRAIN',
  'BHS,BAHAMAS',
  'BIH,BOSNIA AND HERZEGOVINA',
  'BLR,BELARUS',
  'BLZ,BELIZE',
  'BMU,BERMUDA',
  'BOL,BOLIVIA',
  'BRA,BRAZIL',
  'BRB,BARBADOS',
  'BRN,BRUNEI DARUSSALAM',
  'BTN,BHUTAN',
  'BVT,BOUVETISLAND',
  'BWA,BOTSWANA',
  'CAF,CENTRAL AFRICAN REPUBLIC',
  'CAN,CANADA',
  'CCK,COCOS ISLANDS',
  'CHE,SWITZERLAND',
  'CHL,CHILE',
  "CHN,PEOPLE'S REPUBLIC OF CHINA",
  "CIV,COTE D'IVOIRE",
  'CMR,CAMEROON',
  'COD,CONGO, THE DEMOCRATIC REPUBLIC OF THE',
  'COG,CONGO',
  'COK,COOK ISLANDS',
  'COL,COLOMBIA',
  'COM,COMOROS',
  'CPV,CAPE VERDE',
  'CRI,COSTA RICA',
  'CUB,CUBA',
  'CUW,CURACAO',
  'CXR,CHRISTMAS ISLAND',
  'CYM,CAYMAN ISLANDS',
  'CYP,CYPRUS',
  'CZE,CZECH REPUBLIC',
  'DDR,GERMAN DEMOCRATIC',
  'DEU,GERMANY',
  'DJI,DJIBOUTI',
  'DMA,DOMINICA',
  'DNK,DENMARK',
  'DOM,DOMINICAN REPUBLIC',
  'DXB,DUBAI',
  'DZA,ALGERIA',
  'ECU,ECUADOR',
  'EGY,EGYPT',
  'ERI,ERITREA',
  'ESH,SAHARAUI',
  'ESH,WESTERN SAMOA',
  'ESP,SPAIN',
  'EST,ESTONIA',
  'ETH,ETHIOPIA',
  'FIN,FINLAND',
  'FJI,FIJI',
  'FLK,FALKLAND ISLANDS',
  'FRA,FRANCE',
  'FRO,FAROE ISLANDS',
  'FSM,MICRONESIA, FEDERATED STATES OF',
  'GAB,GABON',
  'GBR,UNITED KINGDOM',
  'GEO,GEORGIA',
  'GHA,GHANA',
  'GIN,GUINEA',
  'GLP,GUADELOUPE',
  'GMB,GAMBIA',
  'GNB,GUINEA-BISSAU',
  'GNQ,EQUATORIAL GUINEA',
  'GRC,GREECE',
  'GRD,GRENADA',
  'GRL,GREENLAND',
  'GTM,GUATEMALA',
  'GUF,FRENCH GUIANA',
  'GUM,GUAM',
  'GUY,GUYANA',
  'HKG,HONG KONG',
  'HMD,HEARD AND MCDONALD ISLANDS',
  'HND,HONDURAS',
  'HRV,CROATIA',
  'HTI,HAITI',
  'HUN,HUNGARY',
  'IDN,INDONESIA',
  'IND,INDIA',
  'IOT,BRITISH INDIAN OCEAN TERRITORY',
  'IRL,IRELAND',
  'IRN,IRAN, ISLAMIC REPUBLIC OF',
  'IRQ,IRAQ',
  'ISL,ICELAND',
  'ISR,ISRAEL',
  'ITA,ITALY',
  'JAM,JAMAICA',
  'JOR,JORDAN',
  'JPN,JAPAN',
  'KAZ,KAZAKHSTAN',
  'KEN,KENYA',
  'KGZ,KYRGYZSTAN',
  'KHM,CAMBODIA',
  'KIR,KIRIBATI',
  'KNA,SAINT KITTS AND NEVIS',
  'KOR,KOREA REPUBLIC OF',
  'KWT,KUWAIT',
  "LAO,LAO PEOPLE'S DEMOCRATIC REPUBLIC",
  'LBN,LEBANON',
  'LBR,LIBERIA',
  'LBY,LIBYAN ARAB JAMAHIRIYA',
  'LCA,SAINT LUCIA',
  'LIE,LIECHTENSTEIN',
  'LKA,SRI LANKA',
  'LSO,LESOTHO',
  'LTU,LITHUANIA',
  'LUX,LUXEMBOURG',
  'LVA,LATVIA',
  'MAC,MACAO',
  'MAR,MOROCCO',
  'MCO,MONACO',
  'MDA,MOLDOVA',
  'MDG,MADAGASCAR',
  'MDV,MALDIVES',
  'MEX,MEXICO',
  'MHL,MARSHALL ISLANDS',
  'MKD,REPUBLIC OF NORTH MACEDONIA',
  'MLI,MALI',
  'MLT,MALTA',
  'MMR,MYANMAR',
  'MNE,MONTENEGRO',
  'MNG,MONGOLIA',
  'MNP,NORTHERN MARIANA ISLANDS',
  'MOZ,MOZAMBIQUE',
  'MRT,MAURITANIA',
  'MSR,MONTSERRAT',
  'MTQ,MARTINIQUE',
  'MUS,MAURITIUS',
  'MWI,MALAWI',
  'MYS,MALAYSIA',
  'MYT,MAYOTTE',
  'NAM,NAMIBIA',
  'NCL,NEW CALEDONIA',
  'NER,NIGER',
  'NFK,NORFOLK ISLAND',
  'NGA,NIGERIA',
  'NIC,NICARAGUA',
  'NIU,NIUE',
  'NLD,NETHERLANDS',
  'NON,STATELESS',
  'NOR,NORWAY',
  'NPL,NEPAL',
  'NRU,NAURU',
  'NZL,NEW ZEALAND',
  'OMN,OMAN',
  'PAK,PAKISTAN',
  'PAN,PANAMA',
  'PCN,PITCAIRN ISLANDS',
  'PER,PERU',
  'PHL,PHILIPPINES',
  'PLW,PALAU',
  'PNG,PAPUA NEW GUINEA',
  'POL,POLISH',
  'PRI,PUERTO RICO',
  "PRK,KOREA DEMOCRATIC PEOPLE'S REPUBLIC OF",
  'PRT,PORTUGAL',
  'PRY,PARAGUAY',
  'PSE,PALESTINE',
  'PYF,POLYNESIE',
  'QAT,QATAR',
  'REU,REUNION',
  'RKS,KOSOVO',
  'ROC,REPUBLIC OF CHINA(TAIWAN)',
  'ROU,ROMANIA',
  'RSL,REPUBLIC OF SOMALILAND',
  'RUS,RUSSIAN FEDERATION',
  'RWA,RWANDA',
  'SAU,SAUDI ARABIA',
  'SDN,SUDAN',
  'SEN,SENEGAL',
  'SGP,SINGAPORE',
  'SGS,SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS',
  'SHN,SAINT HELENA',
  'SJM,SVALBARD AND JAN MAYEN ISLANDS',
  'SLB,SOLOMON ISLANDS',
  'SLE,SIERRA LEONE',
  'SLV,EL SALVADOR',
  'SMR,SAN MARINO',
  'SOM,SOMALIA',
  'SPM,ST.PIERRE AND MIQUELON',
  'SXM,ST.MAARTEN',
  'SRB,SERBIA',
  'SSD,REPUBLIC OF SOUTH SUDAN',
  'STP,SAO TOME AND PRINCIPE',
  'SUN,U S S R',
  'SUR,SURINAME',
  'SVK,SLOVAK REPUBLIC',
  'SVN,SLOVENIA',
  'SWE,SWEDEN',
  'SWZ,SWAZILAND',
  'SYC,SEYCHELLES',
  'SYR,SYRIAN ARAB REPUBLIC',
  'TCA,TURKS AND CAICOS ISLANDS',
  'TCD,CHAD',
  'TGO,TOGO',
  'THA,THAILAND',
  'TJK,TAJIKISTAN',
  'TKL,TOKELAU',
  'TKM,TURKMEN',
  'TLS,DEMOCRATIC REPUBLIC OF TIMOR-LESTE',
  'TON,TONGA',
  'TTO,TRINIDAD AND TOBAGO',
  'TUN,TUNISIA',
  'TUR,TURKEY',
  'TUV,TUVALU',
  'TZA,TANZANIA, UNITED REPUBLIC OF',
  'UGA,UGANDA',
  'UKR,UKRAINE',
  'UNO,UNITED NATIONS ORGANIZATION',
  'UNA,UNITED NATIONS SPECIALIZED AGENCY',
  'UNK,UNMIK TRAVEL DOCUMENT',
  'UMI,UNITED STATES MINOR OUTLYING ISLANDS',
  'URY,URUGUAY',
  'USA,UNITED STATES',
  'UZB,UZBEKISTAN',
  'VAT,HOLY SEE (VATICAN CITY STATE)',
  'VCT,SAINT VINCENT AND THE GRENADINES',
  'VEN,VENEZUELA',
  'VGB,VIRGIN ISLANDS, BRITISH',
  'VIR,VIRGIN ISLANDS OF UNITED STATES',
  'VNM,VIET NAM',
  'VUT,VANUATU',
  'WLF,WALLIS AND FUTUNA ISLANDS',
  'WSM,SAMOA',
  'YEM,NORTH YEMEN',
  'YEM,YEMEN',
  'YMD,SOUTH YEMEN',
  'YUG,YUGOSLAVIA',
  'ZAF,SOUTH AFRICA',
  'ZAR,ZAIRE',
  'ZMB,ZAMBIA',
  'ZWE,ZIMBABWE',
  'XXA,STATELESS',
  'XXB,REFUGEE',
  'XXC,REFUGEE',
  'XXX,STATELESS',
] as const

/** 電話の国番号(O 列)。'+81 JPN' 形式。工作表2!$R$2:$R$222 */
export const REGION_CODE_OPTIONS = [
  '+1 USA/CAN',
  '+1-246 BRB',
  '+1-268 ATG',
  '+1-284 VGB',
  '+1-340 VIR',
  '+1-345 CYM',
  '+1-441 BMU',
  '+1-473 GRD',
  '+1-649 TCA',
  '+1-664 MSR',
  '+1-670 MNP',
  '+1-671 GUM',
  '+1-758 LCA',
  '+1-767 DMA',
  '+1-784 VCT',
  '+1-809 DOM',
  '+1-868 TTO',
  '+1-869 KNA',
  '+1-876 JAM',
  '+20 EGY',
  '+211 SSD',
  '+212 MAR/ESH',
  '+213 DZA',
  '+216 TUN',
  '+218 LBY',
  '+220 GMB',
  '+221 SEN',
  '+222 MRT',
  '+223 MLI',
  '+224 GIN',
  '+225 CIV',
  '+226 BFA',
  '+227 NER',
  '+228 TGO',
  '+229 BEN',
  '+230 MUS',
  '+231 LBR',
  '+232 SLE',
  '+233 GHA',
  '+234 NGA',
  '+235 TCD',
  '+236 CAF',
  '+237 CMR',
  '+238 CPV',
  '+239 STP',
  '+240 GNQ',
  '+241 GAB',
  '+242 COG',
  '+243 COD',
  '+244 AGO',
  '+245 GNB',
  '+246 IOT',
  '+248 SYC',
  '+249 SDN',
  '+250 RWA',
  '+251 ETH',
  '+252 SOM',
  '+253 DJI',
  '+254 KEN',
  '+255 TZA',
  '+256 UGA',
  '+257 BDI',
  '+258 MOZ',
  '+260 ZMB',
  '+261 MDG',
  '+262 REU/MYT',
  '+263 ZWE',
  '+264 NAM',
  '+265 MWI',
  '+266 LSO',
  '+267 BWA',
  '+268 SWZ',
  '+269 COM',
  '+27 ZAF',
  '+290 SHN',
  '+291 ERI',
  '+297 ABW',
  '+298 FRO',
  '+299 GRL',
  '+30 GRC',
  '+31 NLD',
  '+32 BEL',
  '+33 FRA',
  '+34 ESP',
  '+351 PRT',
  '+352 LUX',
  '+353 IRL',
  '+354 ISL',
  '+355 ALB',
  '+356 MLT',
  '+357 CYP',
  '+358 FIN',
  '+359 BGR',
  '+36 HUN',
  '+370 LTU',
  '+371 LVA',
  '+372 EST',
  '+373 MDA',
  '+374 ARM',
  '+375 BLR',
  '+376 AND',
  '+377 MCO',
  '+378 SMR',
  '+380 UKR',
  '+381 SRB',
  '+382 MNE',
  '+383 RKS',
  '+385 HRV',
  '+386 SVN',
  '+387 BIH',
  '+389 MKD',
  '+39 ITA',
  '+40 ROU',
  '+41 CHE',
  '+420 CZE',
  '+421 SVK',
  '+423 LIE',
  '+43 AUT',
  '+44 GBR',
  '+45 DNK',
  '+46 SWE',
  '+47 NOR',
  '+48 POL',
  '+49 DEU',
  '+500 FLK',
  '+501 BLZ',
  '+502 GTM',
  '+503 SLV',
  '+504 HND',
  '+505 NIC',
  '+506 CRI',
  '+507 PAN',
  '+508 SPM',
  '+509 HTI',
  '+51 PER',
  '+52 MEX',
  '+53 CUB',
  '+54 ARG',
  '+55 BRA',
  '+56 CHL',
  '+57 COL',
  '+58 VEN',
  '+590 GLP',
  '+591 BOL',
  '+592 GUY',
  '+593 ECU',
  '+594 GUF',
  '+595 PRY',
  '+596 MTQ',
  '+597 SUR',
  '+598 URY',
  '+60 MYS',
  '+61 AUS',
  '+62 IDN',
  '+63 PHL',
  '+64 NZL',
  '+65 SGP',
  '+66 THA',
  '+670 TLS',
  '+672 NFK',
  '+673 BRN',
  '+674 NRU',
  '+675 PNG',
  '+676 TON',
  '+677 SLB',
  '+678 VUT',
  '+679 FJI',
  '+680 PLW',
  '+681 WLF',
  '+682 COK',
  '+683 NIU',
  '+685 WSM',
  '+686 KIR',
  '+687 NCL',
  '+688 TUV',
  '+689 PYF',
  '+690 TKL',
  '+691 FSM',
  '+692 MHL',
  '+7 RUS/KAZ',
  '+81 JPN',
  '+82 KOR',
  '+84 VNM',
  '+850 PRK',
  '+852 HKG',
  '+853 MAC',
  '+855 KHM',
  '+856 LAO',
  '+86 CHN',
  '+880 BGD',
  '+886 ROC',
  '+90 TUR',
  '+91 IND',
  '+92 PAK',
  '+93 AFG',
  '+94 LKA',
  '+95 MMR',
  '+960 MDV',
  '+961 LBN',
  '+962 JOR',
  '+963 SYR',
  '+964 IRQ',
  '+965 KWT',
  '+966 SAU',
  '+967 YEM',
  '+968 OMN',
  '+970 PSE',
  '+971 ARE',
  '+972 ISR',
  '+973 BHR',
  '+974 QAT',
  '+975 BTN',
  '+976 MNG',
  '+977 NPL',
  '+98 IRN',
  '+992 TJK',
  '+993 TKM',
  '+994 AZE',
  '+995 GEO',
  '+996 KGZ',
  '+998 UZB',
] as const

/** 航空会社(U / Z 列)。'BR : EVA Air' 形式。工作表2!$S$2:$S$109 */
export const FLIGHT_CODE_OPTIONS = [
  '3K : JetStarAsia',
  '3U : Sichuan Airlines Co. Ltd.',
  '4V : Fly Gangwon',
  '5J : Cebu Pacific Air',
  '5X : UPS Airlines',
  '5Y : Atlas Air',
  '7C : JEJUAIR',
  '7G : StarFlyer',
  '8L : Lucky Air',
  '8M : Myanmar Airways International',
  '9C : Spring Airlines',
  '9G : Sun PhuQuocAirways',
  'AA : American Airlines',
  'AC : Air Canada',
  'AE : Mandarin Airlines',
  'AF : Air France',
  'AI : Air India (NACIL)',
  'AK : AirAsia Berhad',
  'AV : AVIANCA',
  'AZ : Alitalia',
  'B7 : UNI Airways',
  'BC : Skymark Airlines',
  'BI : Royal Brunei',
  'BL : Pacific Airlines',
  'BR : EVA Air',
  'BX : Air Busan',
  'C8 : Cargolux Italia',
  'CA : Air China Limited',
  'CF : China Portal Airlines',
  'CI : China Airlines',
  'CK : China Cargo Airlines Ltd.',
  'CM : COPA Airlines',
  'CO : Continental Airlines',
  'CV : Cargolux S.A.',
  'CX : Cathay Pacific',
  'CZ : China Southern Airlines',
  'D7 : AirAsia X',
  'DA : Daily Air',
  'DL : Delta Air Lines',
  'EH : ANA Wings',
  'EK : Emirates',
  'EY : Etihad Airways',
  'FD : Thai Air Asia',
  'FM : Shanghai Airlines',
  'FX : Federal Express',
  'GA : Garuda',
  'GK : Jetstar Air',
  'HA : Hawaiian Airlines',
  'HB : Greater Bay Airline',
  'HO : Juneyao Airlines',
  'HU : Hainan Airlines',
  'HX : Hong Kong Airlines',
  'IT : Tigerair Taiwan',
  'JL : Japan Airlines',
  'JX : STARLUX Airlines',
  'K4 : Kalitta Air',
  'KD : Western Global Airlines',
  'KE : Korean Air',
  'KL : KLM',
  'KZ : Nippon Cargo Airlines (NCA)',
  'LD : Air Hong Kong',
  'LG : Luxair',
  'LH : Lufthansa Cargo AG',
  'LJ : Jin Air',
  'LY : EL AL',
  'MF : Xiamen Airlines',
  'MH : Malaysia Airlines',
  'MM : FLY PEACH',
  'MU : China Eastern',
  'NH : All Nippon Airways',
  'NU : Japan TransOcean Air',
  'NX : Air Macau',
  'NZ : Air New Zealand',
  'O3 : SF AIRLINES',
  'OD : Malindo Air',
  'OS : Austrian',
  'OZ : Asiana',
  'P7 : Palau Airways',
  'PG : Bangkok Airways Co., Ltd.',
  'PO : Polar Air Cargo',
  'PR : PAL',
  'QD : JC International Airlines',
  'QF : Qantas',
  'QH : Bamboo Airways',
  'RF : Aero K Airlines',
  'RH : Hong Kong Air Cargo',
  'RW : Royal Air Charter Service',
  'SC : Shandong Airlines Co., Ltd.',
  'SL : Thai Lion Air',
  'SQ : Singapore Airlines',
  'ST : Skyvision Aviation Corp',
  'TG : Thai Airways International',
  'TK : THY - Turkish Airlines',
  'TR : Scoot Airways',
  'TW : TWay Air',
  'TZ : Scoot Airways',
  'UA : United Airlines',
  'UK : Vistara',
  'UO : Hong Kong Express Airways',
  'UX : Air Europa',
  'VJ : VietJet Air',
  'VN : Vietnam Airlines',
  'VU : Vietravel Airlines',
  'VZ : Thai Vietjet Air',
  'Y8 : Yangtze River Express',
  'Z2 : Philippines AirAsia',
  'ZE : Eastar Jet',
  'ZH : Shenzhen Airlines Co. Ltd.',
] as const

/** 入出国の手段(T / Y 列)。工作表2!$T$2:$T$3 */
export const MODE_OF_TRAVEL_OPTIONS = ['AIR', 'SEA'] as const

// ---------------------------------------------------------------------------
// 国籍に応じた Visa Type の切り替え
//
// テンプレートの M 列には次のデータ入力規則が張られている(sheet1.xml より):
//   INDIRECT( IF(I2="ROC,REPUBLIC OF CHINA(TAIWAN)", "TaiwanVisa",
//     IF(OR(I2="HKG,HONG KONG",I2="MAC,MACAO",I2="CHN,PEOPLE'S REPUBLIC OF CHINA"),
//        "ChinaVisa", "OtherVisa" )))
// つまり Visa Type の選択肢は国籍(I 列)で決まる。ここはその式を TypeScript に
// 写したもので、判定条件はテンプレートの式が唯一の根拠。
// ---------------------------------------------------------------------------

/** 国籍 = 台湾。Visa Type が VISA_TYPE_TAIWAN になる */
export const NATIONALITY_TAIWAN = 'ROC,REPUBLIC OF CHINA(TAIWAN)'

/** 国籍 = 香港・マカオ・中国。Visa Type が VISA_TYPE_CHINA になる */
export const NATIONALITIES_CHINA = [
  'HKG,HONG KONG',
  'MAC,MACAO',
  "CHN,PEOPLE'S REPUBLIC OF CHINA",
] as const

/** 国籍に対応する Visa Type の選択肢を返す */
export function visaTypeOptionsFor(nationality: string): ReadonlyArray<string> {
  if (nationality === NATIONALITY_TAIWAN) return VISA_TYPE_TAIWAN
  if (NATIONALITIES_CHINA.some((code) => code === nationality)) {
    return VISA_TYPE_CHINA
  }
  return VISA_TYPE_OTHER
}

/**
 * Visa Number(N 列)を書く必要があるか。
 *
 * 免簽證(ビザ免除)と未具入國許可(許可不要)には対応する番号が存在しない。
 * テンプレートの条件付き書式も、この 2 つのときだけ N 列を塗り分けている。
 * 番号の無い区分で入力欄を出すと「何を書けばいいのか」で必ず詰まるので、
 * UI 側はこの判定で欄ごと隠す。
 */
export function needsVisaNumber(visaType: string): boolean {
  return (
    visaType !== '免簽證 Visa-Exempt(include TAC)' &&
    visaType !== '未具入國許可 Permit-Exempt'
  )
}

/** 探親(親族訪問)。AD/AE 列(親族の氏名・電話)が要る目的 */
export const PURPOSE_VISIT_RELATIVE = '5.探親 Visit Relative'

/** 其他(その他)。AF 列(理由)が要る目的 */
export const PURPOSE_OTHERS = '10.其他 Others'

/**
 * 日本のパスポートで観光に行く、という最も多い組み合わせを既定値にする。
 * 選択肢が 256 件ある欄を全員が毎回探すのは現実的ではない。
 */
export const DEFAULT_NATIONALITY = 'JPN,JAPAN'
export const DEFAULT_REGION_CODE = '+81 JPN'
export const DEFAULT_VISA_TYPE = '免簽證 Visa-Exempt(include TAC)'
export const DEFAULT_PURPOSE = '3.觀光 Sightseeing / Travel / Leisure'
export const DEFAULT_ACCOMMODATION = 'Hotel Name'

/**
 * 航空会社の 2 レターコードを、リスト値('BR : EVA Air')に解決する。
 *
 * AI には 'BR' のようなコードだけを返させる(会社名まで正確に一致させるのは
 * 無理があり、'EVA Airways' のような表記揺れで必ず外れる)。突き合わせは
 * コード + ' : ' の前方一致で行い、リストに無ければ null を返す。
 * 近そうな候補で代用はしない。別の航空会社の便として登録されるほうが、
 * 空欄のまま人間に気付いてもらうより有害なため。
 */
export function resolveFlightCode(airlineCode: string): string | null {
  const prefix = `${airlineCode.trim().toUpperCase()} : `
  return FLIGHT_CODE_OPTIONS.find((code) => code.startsWith(prefix)) ?? null
}
