import type { City } from './types'

/**
 * ヨーロッパ主要都市カタログ。
 * 座標は移動時間の概算(大圏距離)に使う。
 * enName / iata は外部の移動検索サイトへのディープリンク(travelLinks.ts)に使う。
 */
export const cityCatalog: Array<City> = [
  // フランス
  {
    id: 'paris',
    name: 'パリ',
    enName: 'Paris',
    country: 'フランス',
    iata: 'CDG',
    dbStation: 'Paris',
    lat: 48.8566,
    lng: 2.3522,
    landmass: 'continental',
  },
  {
    id: 'nice',
    name: 'ニース',
    enName: 'Nice',
    country: 'フランス',
    iata: 'NCE',
    dbStation: 'Nice',
    lat: 43.7102,
    lng: 7.262,
    landmass: 'continental',
  },
  {
    id: 'lyon',
    name: 'リヨン',
    enName: 'Lyon',
    country: 'フランス',
    iata: 'LYS',
    dbStation: 'Lyon',
    lat: 45.764,
    lng: 4.8357,
    landmass: 'continental',
  },
  {
    id: 'marseille',
    name: 'マルセイユ',
    enName: 'Marseille',
    country: 'フランス',
    iata: 'MRS',
    dbStation: 'Marseille',
    lat: 43.2965,
    lng: 5.3698,
    landmass: 'continental',
  },
  {
    id: 'strasbourg',
    name: 'ストラスブール',
    enName: 'Strasbourg',
    country: 'フランス',
    iata: 'SXB',
    dbStation: 'Strasbourg',
    lat: 48.5734,
    lng: 7.7521,
    landmass: 'continental',
  },
  {
    id: 'bordeaux',
    name: 'ボルドー',
    enName: 'Bordeaux',
    country: 'フランス',
    iata: 'BOD',
    dbStation: 'Bordeaux',
    lat: 44.8378,
    lng: -0.5792,
    landmass: 'continental',
  },
  // イギリス・アイルランド
  {
    id: 'london',
    name: 'ロンドン',
    enName: 'London',
    country: 'イギリス',
    iata: 'LHR',
    dbStation: 'London',
    lat: 51.5074,
    lng: -0.1278,
    landmass: 'britain',
  },
  {
    id: 'edinburgh',
    name: 'エディンバラ',
    enName: 'Edinburgh',
    country: 'イギリス',
    iata: 'EDI',
    dbStation: 'Edinburgh',
    lat: 55.9533,
    lng: -3.1883,
    landmass: 'britain',
  },
  {
    id: 'dublin',
    name: 'ダブリン',
    enName: 'Dublin',
    country: 'アイルランド',
    iata: 'DUB',
    dbStation: 'Dublin',
    lat: 53.3498,
    lng: -6.2603,
    landmass: 'ireland',
  },
  // イタリア
  {
    id: 'rome',
    name: 'ローマ',
    enName: 'Rome',
    country: 'イタリア',
    iata: 'FCO',
    dbStation: 'Rome',
    lat: 41.9028,
    lng: 12.4964,
    landmass: 'continental',
  },
  {
    id: 'florence',
    name: 'フィレンツェ',
    enName: 'Florence',
    country: 'イタリア',
    iata: 'FLR',
    dbStation: 'Florence',
    lat: 43.7696,
    lng: 11.2558,
    landmass: 'continental',
  },
  {
    id: 'venice',
    name: 'ヴェネツィア',
    enName: 'Venice',
    country: 'イタリア',
    iata: 'VCE',
    dbStation: 'Venice',
    lat: 45.4408,
    lng: 12.3155,
    landmass: 'continental',
  },
  {
    id: 'milan',
    name: 'ミラノ',
    enName: 'Milan',
    country: 'イタリア',
    iata: 'MXP',
    dbStation: 'Milano Centrale',
    lat: 45.4642,
    lng: 9.19,
    landmass: 'continental',
  },
  {
    id: 'naples',
    name: 'ナポリ',
    enName: 'Naples',
    country: 'イタリア',
    iata: 'NAP',
    dbStation: 'Naples',
    lat: 40.8518,
    lng: 14.2681,
    landmass: 'continental',
  },
  // スペイン・ポルトガル
  {
    id: 'barcelona',
    name: 'バルセロナ',
    enName: 'Barcelona',
    country: 'スペイン',
    iata: 'BCN',
    dbStation: 'Barcelona',
    lat: 41.3874,
    lng: 2.1686,
    landmass: 'continental',
  },
  {
    id: 'madrid',
    name: 'マドリード',
    enName: 'Madrid',
    country: 'スペイン',
    iata: 'MAD',
    dbStation: 'Madrid',
    lat: 40.4168,
    lng: -3.7038,
    landmass: 'continental',
  },
  {
    id: 'seville',
    name: 'セビリア',
    enName: 'Seville',
    country: 'スペイン',
    iata: 'SVQ',
    dbStation: 'Sevilla Santa Justa',
    lat: 37.3891,
    lng: -5.9845,
    landmass: 'continental',
  },
  {
    id: 'granada',
    name: 'グラナダ',
    enName: 'Granada',
    country: 'スペイン',
    iata: 'GRX',
    dbStation: 'Granada',
    lat: 37.1773,
    lng: -3.5986,
    landmass: 'continental',
  },
  {
    id: 'lisbon',
    name: 'リスボン',
    enName: 'Lisbon',
    country: 'ポルトガル',
    iata: 'LIS',
    dbStation: 'Lisbon',
    lat: 38.7223,
    lng: -9.1393,
    landmass: 'continental',
  },
  {
    id: 'porto',
    name: 'ポルト',
    enName: 'Porto',
    country: 'ポルトガル',
    iata: 'OPO',
    dbStation: 'Porto',
    lat: 41.1579,
    lng: -8.6291,
    landmass: 'continental',
  },
  // ベネルクス
  {
    id: 'amsterdam',
    name: 'アムステルダム',
    enName: 'Amsterdam',
    country: 'オランダ',
    iata: 'AMS',
    dbStation: 'Amsterdam',
    lat: 52.3676,
    lng: 4.9041,
    landmass: 'continental',
  },
  {
    id: 'brussels',
    name: 'ブリュッセル',
    enName: 'Brussels',
    country: 'ベルギー',
    iata: 'BRU',
    dbStation: 'Brussels',
    lat: 50.8503,
    lng: 4.3517,
    landmass: 'continental',
  },
  {
    id: 'bruges',
    name: 'ブルージュ',
    enName: 'Bruges',
    country: 'ベルギー',
    iata: null,
    dbStation: 'Bruges',
    lat: 51.2093,
    lng: 3.2247,
    landmass: 'continental',
  },
  // ドイツ
  {
    id: 'berlin',
    name: 'ベルリン',
    enName: 'Berlin',
    country: 'ドイツ',
    iata: 'BER',
    dbStation: 'Berlin',
    lat: 52.52,
    lng: 13.405,
    landmass: 'continental',
  },
  {
    id: 'munich',
    name: 'ミュンヘン',
    enName: 'Munich',
    country: 'ドイツ',
    iata: 'MUC',
    dbStation: 'Munich',
    lat: 48.1351,
    lng: 11.582,
    landmass: 'continental',
  },
  {
    id: 'frankfurt',
    name: 'フランクフルト',
    enName: 'Frankfurt',
    country: 'ドイツ',
    iata: 'FRA',
    dbStation: 'Frankfurt',
    lat: 50.1109,
    lng: 8.6821,
    landmass: 'continental',
  },
  {
    id: 'cologne',
    name: 'ケルン',
    enName: 'Cologne',
    country: 'ドイツ',
    iata: 'CGN',
    dbStation: 'Cologne',
    lat: 50.9375,
    lng: 6.9603,
    landmass: 'continental',
  },
  // 中欧
  {
    id: 'vienna',
    name: 'ウィーン',
    enName: 'Vienna',
    country: 'オーストリア',
    iata: 'VIE',
    dbStation: 'Vienna',
    lat: 48.2082,
    lng: 16.3738,
    landmass: 'continental',
  },
  {
    id: 'salzburg',
    name: 'ザルツブルク',
    enName: 'Salzburg',
    country: 'オーストリア',
    iata: 'SZG',
    dbStation: 'Salzburg',
    lat: 47.8095,
    lng: 13.055,
    landmass: 'continental',
  },
  {
    id: 'hallstatt',
    name: 'ハルシュタット',
    enName: 'Hallstatt',
    country: 'オーストリア',
    iata: null,
    dbStation: 'Hallstatt',
    lat: 47.5622,
    lng: 13.6493,
    landmass: 'continental',
  },
  {
    id: 'prague',
    name: 'プラハ',
    enName: 'Prague',
    country: 'チェコ',
    iata: 'PRG',
    dbStation: 'Prague',
    lat: 50.0755,
    lng: 14.4378,
    landmass: 'continental',
  },
  {
    id: 'budapest',
    name: 'ブダペスト',
    enName: 'Budapest',
    country: 'ハンガリー',
    iata: 'BUD',
    dbStation: 'Budapest',
    lat: 47.4979,
    lng: 19.0402,
    landmass: 'continental',
  },
  {
    id: 'krakow',
    name: 'クラクフ',
    enName: 'Krakow',
    country: 'ポーランド',
    iata: 'KRK',
    dbStation: 'Krakow',
    lat: 50.0647,
    lng: 19.945,
    landmass: 'continental',
  },
  // スイス
  {
    id: 'zurich',
    name: 'チューリッヒ',
    enName: 'Zurich',
    country: 'スイス',
    iata: 'ZRH',
    dbStation: 'Zurich',
    lat: 47.3769,
    lng: 8.5417,
    landmass: 'continental',
  },
  {
    id: 'geneva',
    name: 'ジュネーブ',
    enName: 'Geneva',
    country: 'スイス',
    iata: 'GVA',
    dbStation: 'Geneva',
    lat: 46.2044,
    lng: 6.1432,
    landmass: 'continental',
  },
  {
    id: 'interlaken',
    name: 'インターラーケン',
    enName: 'Interlaken',
    country: 'スイス',
    iata: null,
    dbStation: 'Interlaken',
    lat: 46.6863,
    lng: 7.8632,
    landmass: 'continental',
  },
  {
    id: 'lucerne',
    name: 'ルツェルン',
    enName: 'Lucerne',
    country: 'スイス',
    iata: null,
    dbStation: 'Lucerne',
    lat: 47.0502,
    lng: 8.3093,
    landmass: 'continental',
  },
  // 北欧
  {
    id: 'copenhagen',
    name: 'コペンハーゲン',
    enName: 'Copenhagen',
    country: 'デンマーク',
    iata: 'CPH',
    dbStation: 'Copenhagen',
    lat: 55.6761,
    lng: 12.5683,
    landmass: 'continental',
  },
  {
    id: 'stockholm',
    name: 'ストックホルム',
    enName: 'Stockholm',
    country: 'スウェーデン',
    iata: 'ARN',
    dbStation: 'Stockholm',
    lat: 59.3293,
    lng: 18.0686,
    landmass: 'continental',
  },
  {
    id: 'oslo',
    name: 'オスロ',
    enName: 'Oslo',
    country: 'ノルウェー',
    iata: 'OSL',
    dbStation: 'Oslo',
    lat: 59.9139,
    lng: 10.7522,
    landmass: 'continental',
  },
  {
    id: 'helsinki',
    name: 'ヘルシンキ',
    enName: 'Helsinki',
    country: 'フィンランド',
    iata: 'HEL',
    dbStation: 'Helsinki',
    lat: 60.1699,
    lng: 24.9384,
    landmass: 'continental',
  },
  // 南東欧・その他
  {
    id: 'athens',
    name: 'アテネ',
    enName: 'Athens',
    country: 'ギリシャ',
    iata: 'ATH',
    dbStation: 'Athens',
    lat: 37.9838,
    lng: 23.7275,
    landmass: 'continental',
  },
  {
    id: 'santorini',
    name: 'サントリーニ',
    enName: 'Santorini',
    country: 'ギリシャ',
    iata: 'JTR',
    dbStation: null,
    lat: 36.3932,
    lng: 25.4615,
    landmass: 'santorini',
  },
  {
    id: 'dubrovnik',
    name: 'ドゥブロヴニク',
    enName: 'Dubrovnik',
    country: 'クロアチア',
    iata: 'DBV',
    dbStation: null,
    lat: 42.6507,
    lng: 18.0944,
    landmass: 'continental',
  },
  {
    id: 'ljubljana',
    name: 'リュブリャナ',
    enName: 'Ljubljana',
    country: 'スロベニア',
    iata: 'LJU',
    dbStation: 'Ljubljana',
    lat: 46.0569,
    lng: 14.5058,
    landmass: 'continental',
  },
  {
    id: 'malta',
    name: 'マルタ',
    enName: 'Malta',
    country: 'マルタ',
    iata: 'MLA',
    dbStation: null,
    lat: 35.8989,
    lng: 14.5146,
    landmass: 'malta',
  },
]

const cityMap = new Map(cityCatalog.map((city) => [city.id, city]))

export function getCity(cityId: string): City | undefined {
  return cityMap.get(cityId)
}

export function cityName(cityId: string): string {
  return cityMap.get(cityId)?.name ?? cityId
}
