/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsActualSizeLayoutIndexRouteImport } from './routes/tools/actual-size-layout/index'
import { Route as ToolsDrumRollIndexRouteImport } from './routes/tools/drum-roll/index'
import { Route as ToolsLicenseLayoutIndexRouteImport } from './routes/tools/license-layout/index'
import { Route as ToolsTaiwanArrivalCardIndexRouteImport } from './routes/tools/taiwan-arrival-card/index'
import { Route as ToolsTripNotesIndexRouteImport } from './routes/tools/trip-notes/index'
import { Route as ToolsTripSchedulerIndexRouteImport } from './routes/tools/trip-scheduler/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsActualSizeLayoutIndexRoute =
  ToolsActualSizeLayoutIndexRouteImport.update({
    id: '/tools/actual-size-layout/',
    path: '/tools/actual-size-layout/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsDrumRollIndexRoute = ToolsDrumRollIndexRouteImport.update({
  id: '/tools/drum-roll/',
  path: '/tools/drum-roll/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsLicenseLayoutIndexRoute = ToolsLicenseLayoutIndexRouteImport.update({
  id: '/tools/license-layout/',
  path: '/tools/license-layout/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTaiwanArrivalCardIndexRoute =
  ToolsTaiwanArrivalCardIndexRouteImport.update({
    id: '/tools/taiwan-arrival-card/',
    path: '/tools/taiwan-arrival-card/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ToolsTripNotesIndexRoute = ToolsTripNotesIndexRouteImport.update({
  id: '/tools/trip-notes/',
  path: '/tools/trip-notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTripSchedulerIndexRoute = ToolsTripSchedulerIndexRouteImport.update({
  id: '/tools/trip-scheduler/',
  path: '/tools/trip-scheduler/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tools/actual-size-layout/': typeof ToolsActualSizeLayoutIndexRoute
  '/tools/drum-roll/': typeof ToolsDrumRollIndexRoute
  '/tools/license-layout/': typeof ToolsLicenseLayoutIndexRoute
  '/tools/taiwan-arrival-card/': typeof ToolsTaiwanArrivalCardIndexRoute
  '/tools/trip-notes/': typeof ToolsTripNotesIndexRoute
  '/tools/trip-scheduler/': typeof ToolsTripSchedulerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tools/actual-size-layout': typeof ToolsActualSizeLayoutIndexRoute
  '/tools/drum-roll': typeof ToolsDrumRollIndexRoute
  '/tools/license-layout': typeof ToolsLicenseLayoutIndexRoute
  '/tools/taiwan-arrival-card': typeof ToolsTaiwanArrivalCardIndexRoute
  '/tools/trip-notes': typeof ToolsTripNotesIndexRoute
  '/tools/trip-scheduler': typeof ToolsTripSchedulerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tools/actual-size-layout/': typeof ToolsActualSizeLayoutIndexRoute
  '/tools/drum-roll/': typeof ToolsDrumRollIndexRoute
  '/tools/license-layout/': typeof ToolsLicenseLayoutIndexRoute
  '/tools/taiwan-arrival-card/': typeof ToolsTaiwanArrivalCardIndexRoute
  '/tools/trip-notes/': typeof ToolsTripNotesIndexRoute
  '/tools/trip-scheduler/': typeof ToolsTripSchedulerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/tools/actual-size-layout/'
    | '/tools/drum-roll/'
    | '/tools/license-layout/'
    | '/tools/taiwan-arrival-card/'
    | '/tools/trip-notes/'
    | '/tools/trip-scheduler/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tools/actual-size-layout'
    | '/tools/drum-roll'
    | '/tools/license-layout'
    | '/tools/taiwan-arrival-card'
    | '/tools/trip-notes'
    | '/tools/trip-scheduler'
  id:
    | '__root__'
    | '/'
    | '/tools/actual-size-layout/'
    | '/tools/drum-roll/'
    | '/tools/license-layout/'
    | '/tools/taiwan-arrival-card/'
    | '/tools/trip-notes/'
    | '/tools/trip-scheduler/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolsActualSizeLayoutIndexRoute: typeof ToolsActualSizeLayoutIndexRoute
  ToolsDrumRollIndexRoute: typeof ToolsDrumRollIndexRoute
  ToolsLicenseLayoutIndexRoute: typeof ToolsLicenseLayoutIndexRoute
  ToolsTaiwanArrivalCardIndexRoute: typeof ToolsTaiwanArrivalCardIndexRoute
  ToolsTripNotesIndexRoute: typeof ToolsTripNotesIndexRoute
  ToolsTripSchedulerIndexRoute: typeof ToolsTripSchedulerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/actual-size-layout/': {
      id: '/tools/actual-size-layout/'
      path: '/tools/actual-size-layout'
      fullPath: '/tools/actual-size-layout/'
      preLoaderRoute: typeof ToolsActualSizeLayoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/drum-roll/': {
      id: '/tools/drum-roll/'
      path: '/tools/drum-roll'
      fullPath: '/tools/drum-roll/'
      preLoaderRoute: typeof ToolsDrumRollIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/license-layout/': {
      id: '/tools/license-layout/'
      path: '/tools/license-layout'
      fullPath: '/tools/license-layout/'
      preLoaderRoute: typeof ToolsLicenseLayoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/taiwan-arrival-card/': {
      id: '/tools/taiwan-arrival-card/'
      path: '/tools/taiwan-arrival-card'
      fullPath: '/tools/taiwan-arrival-card/'
      preLoaderRoute: typeof ToolsTaiwanArrivalCardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/trip-notes/': {
      id: '/tools/trip-notes/'
      path: '/tools/trip-notes'
      fullPath: '/tools/trip-notes/'
      preLoaderRoute: typeof ToolsTripNotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/trip-scheduler/': {
      id: '/tools/trip-scheduler/'
      path: '/tools/trip-scheduler'
      fullPath: '/tools/trip-scheduler/'
      preLoaderRoute: typeof ToolsTripSchedulerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolsActualSizeLayoutIndexRoute: ToolsActualSizeLayoutIndexRoute,
  ToolsDrumRollIndexRoute: ToolsDrumRollIndexRoute,
  ToolsLicenseLayoutIndexRoute: ToolsLicenseLayoutIndexRoute,
  ToolsTaiwanArrivalCardIndexRoute: ToolsTaiwanArrivalCardIndexRoute,
  ToolsTripNotesIndexRoute: ToolsTripNotesIndexRoute,
  ToolsTripSchedulerIndexRoute: ToolsTripSchedulerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
