/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsLicenseLayoutIndexRouteImport } from './routes/tools/license-layout/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsLicenseLayoutIndexRoute = ToolsLicenseLayoutIndexRouteImport.update({
  id: '/tools/license-layout/',
  path: '/tools/license-layout/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tools/license-layout': typeof ToolsLicenseLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tools/license-layout': typeof ToolsLicenseLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tools/license-layout/': typeof ToolsLicenseLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tools/license-layout'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tools/license-layout'
  id: '__root__' | '/' | '/tools/license-layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ToolsLicenseLayoutIndexRoute: typeof ToolsLicenseLayoutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/license-layout/': {
      id: '/tools/license-layout/'
      path: '/tools/license-layout'
      fullPath: '/tools/license-layout'
      preLoaderRoute: typeof ToolsLicenseLayoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ToolsLicenseLayoutIndexRoute: ToolsLicenseLayoutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
